Need to convert method to a string before calling upcase on it.
On my Mac running 10.8, failure to do so yields the following error:

NoMethodError: undefined method `upcase' for :post:Symbol